### PR TITLE
Fix Shibboleth account creation not working since 2.0.0 #488

### LINKED ISSUE #488: Shibboleth account creation not working since 2.0.0
Hi,
we already made a post to the seafile educational forum, but without reply. Perhaps it's better to place such bugs here.

Since version 2.0.0 Seadroid crashes, if you try to create a Shibboleth account using https.
At least when connecting to our server.

The following patch at least fixes the crash and makes account creation work, but after creating the account, seadroid returns to the form, where the user entered the Shibboleth server URL.
You can the go back and the account is usable.
Obviously the real fix should perform better than that, but currently Seadroid simply doesn't work for new users, because they can't create an account.

```
diff --git a/app/src/main/java/com/seafile/seadroid2/account/ui/ShibbolethAuthorizeActivity.java b/app/src/main/java/com/seafile/seadroid2/account/ui/ShibbolethAuthorizeActivit
index 178f327..ecebf0b 100644
--- a/app/src/main/java/com/seafile/seadroid2/account/ui/ShibbolethAuthorizeActivity.java
+++ b/app/src/main/java/com/seafile/seadroid2/account/ui/ShibbolethAuthorizeActivity.java
@@ -186,8 +186,10 @@ public class ShibbolethAuthorizeActivity extends BaseActivity implements Toolbar
     }
 
     private void returnAccount(Account account) {
-        if (account == null)
-            finish();
+        if (account == null) {
+            //finish();
+            return;
+        }
 
         Intent retData = new Intent();
         retData.putExtras(getIntent());
```

Hope this gets fixed soon. We first reported this critical bug 16 days ago.

### PR DESCRIPTION
**Pull request by Logan676**
fix #488

### CODE REVIEW

**Comment by egroeper** [comment]
Like said in #488. This fixes the issues, but additionally deactivates certificate checks, which is a really bad idea.
Please don't merge this in its current state.

**Comment by egroeper** [comment]
Looks fine to me. Works as expected here.
Thanks :-)

**Comment by Logan676** [comment]
> Does it mean it accepts all certificates in any case?
yes, but I have fixed the error, see 9b512cedcf531d47b70988e29c392beed4049601

**Comment by shoeper** [comment]
Great :)

**Pull request merged**
