### PR TITLE
Enable TLSv1.3

### LINKED ISSUE #890: Can't establish TLS connection to Seafile Server on Android 10
Hi,

I'm running a seafile server with a caddy server as a reverse proxy, using TLS 1.3 and a Elliptic Curve 256 certificate. With the pc client (linux and windows) version >= 8, I can connect and everything works fine. But the android client complains about the certificate. It has the same error message as cited in issue #599.
The comments on the issue #599 say that's due to lack of support for TLS 1.3 on the system libraries, but Android 10 (according to [this](https://developer.android.com/about/versions/10/features#tls-1.3)) has support for TLS 1.3, so I'm not sure what the issue is.
Any ideas?

### PR DESCRIPTION
**Pull request by louisroyer**
Closes #890.

### CODE REVIEW

**Comment by louisroyer** [comment]
Tested on android 11 (LineageOS 18.1-202110921-NIGHTLY-X00TD), with a TLS1.3 only server.

**Comment by turski** [comment]
Tested on Android 11, with TLSv1.3 only server. Works.

**Comment by n0x-io** [comment]
Tested on Android 11 `LineageOS 18.1-20220302-microG-cheesburger` with a TLS1.3 only server 
(Parameters configured to [these Mozilla SSL Config guidelines](https://ssl-config.mozilla.org/#server=nginx&version=1.18.0&config=modern&openssl=1.1.1k&guideline=5.6))

Works really well! Thank you for this fix!

**Comment by AlbertWeichselbraun** [comment]
I tested the patch with Android 12 and different TLS versions on the server (including a TLS 1.3 only setting).
=> it really works well.

It would be great, if this feature would also be available in the official builds.

**Comment by louisroyer** [comment]
Hi @freeplant, could you please review this PR?

**Comment by YodaCa** [comment]
Is client certificate auth implemented?

**Comment by luckyycode** [comment]
Is it going to be merged?

**Comment by Josue-T** [comment]
Any news ? It's really enjoying that this app still not support TLS 1.3.

**Comment by freeplant** [comment]
We will review the PR in the next month.

**Comment by leahoswald** [comment]
Any news? Its three months since your post.

**Pull request merged**
