### PR TITLE
Make explicit manual refreshs hit the server

### PR DESCRIPTION
**Pull request by 0x64746b**
So far pull-to-refresh hits the local caches for repos, dirs and files, missing
current changes on the server.

This commit `forceRefresh`es the view so the server is hit and changes induced
by other clients are synced.

Fixes haiwen/seadroid#558.

### CODE REVIEW

**Comment by shoeper** [comment]
There is an issue with this. If users download a folder, are offline and want to access the local data it wouldn't work with this PR anymore as far as I can see.

**Comment by 0x64746b** [comment]
@shoeper Why would that be?

1. I'd expect the change to only come into play if the user explicitly did a pull-to-refresh, not when just entering a dir?
2. If the [device is offline](https://github.com/haiwen/seadroid/blob/master/app/src/main/java/com/seafile/seadroid2/ui/fragment/ReposFragment.java#L370), the repos/dirents will always be [fetched from the cache](https://github.com/haiwen/seadroid/blob/master/app/src/main/java/com/seafile/seadroid2/ui/fragment/ReposFragment.java#L371)?

Am I missing sth?
dtk

**Comment by shoeper** [comment]
Yeah, looks like it works like it should with your patch.

**Comment by Logan676** [comment]
e44a97ea6e33ec5615ab4a71c91f574b420512a3

**Pull request merged**
