### PR TITLE
Allow to show multiline error message in dialog

### PR DESCRIPTION
**Pull request by max32002**

### CODE REVIEW

**Comment by max32002** [comment]
sort file and dir in PathChooser Activity.

**Comment by max32002** [comment]
improve upload speed

**Comment by max32002** [comment]
sort repo on path chooser activity

**Comment by freeplant** [comment]
Can you add the code "sort repo on path chooser activity" to an individual branch and send a PR?

**Comment by max32002** [comment]
How about you add the code to an individual branch, I clone and fork the project again?

**Comment by shoeper** [comment]
`git checkout -b new_branch_name`

**Pull request closed without merging**
