### PR TITLE
SettingsFragment: Disable camera upload when sync globally disabled

### PR DESCRIPTION
**Pull request by forouher**
- The user can globally disable all sync in Android (via Settings -> Accounts -> Sync Automatically).
In that case, our camera upload will no longer work. To avoid user confusion, we should check for
that and gray out the camera upload entries in the SettingsFragment.

- Also add onResume() to refresh the fragment when necessary.

### CODE REVIEW

**Comment by forouher** [comment]
this addresses issue #505 , btw.

**Comment by jult** [comment]
Just graying it out is not very friendly, does it also tell the user why it is grayed out? If so, then disregard my comment.

**Comment by Logan676** [comment]
This patch works great but unfortunately it has disabled syncing feature on those *rom-customized* account-syncing-globally-disabled Android devices. That leads up to a bad user experience on devices running those customized roms.

So I will revert the two commits and maybe it\`s better to just toast a warning instead of disable the option.

**Comment by shoeper** [comment]
I disagree. Without global sync it didn't work before as well (that was the reason forouher submitted this patch - at least this is what I understood). So this is a warning making the user know about it. Without the user will be able to enable it but it won't work. Furthermore it's a really bad idea do disable system core features like SyncProvider in a custom rom. It is really nothing we should care too much about.

**Comment by freeplant** [comment]
In China, there are many vendors disable the SyncProvider. Like my phone, with the brand name Nubio, in the old version, the photo sync could work. After changing to use SyncProvider, I need to manually click the "sync now" button in "system settings account -> third party account -> Seafile". If this feature is totally disabled as in this branch, the photo sync can't work on my phone.

**Comment by shoeper** [comment]
Ok, but then it's not working automatically anymore. Maybe this could be changed to still allow the user to change the settings but warn him at the same time that it'll only work autmatically when global sync is enabled.
Don't know what vendors did have in mind disabling the SyncProvider.

**Comment by forouher** [comment]
There might be a third option: enable Global Sync through code:

At the end of the camera upload configuration:

1. Check if sync is globally off - ContentResolver.getMasterSyncAutomatically()
2. If no: Show choice dialog: "Global sync is disabled. Camera upload cannot work without it. Do you want to enable global sync? This will enable sync for *all* installed apps, including other apps you're not thinking of currently."
3a. NO -> abort
3b. YES -> ContentResolver.setMasterSyncAutomatically(true)

**Comment by shoeper** [comment]
As I understood Daniel (@freeplant) the global sync is not available on those devices at all. But if that would work I think it would be a good solution.

**Comment by Logan676** [comment]
@forouher But I wonder if that really works on lower API or customized Anroid OS? Can you build a testing APK or crate a PR? Also will it affect other apps if we enabled `setMasterSyncAutomatically`?

**Comment by forouher** [comment]
@Logan676 I'm not sure if it will work on custom ROMs. I'll write up a short PR for you to test. And yes, it will affect other apps. Therefore Seadroid *really* has to display a very prominent warning.

**Pull request merged**
