### PR TITLE
Migrate seadroid to gradle / Android Studio

### LINKED ISSUE #176: gradle build system
Hi,

I know Android Studio / IntelliJ is still in beta, but I think working with it is more productive than with Eclipse (I use it for my own projects as well). Especially the build process can be heavily simplified by using the gradle build system. Most dependencies can be obtained through maven central and the rest can be included in the source directly without downloading or cloning it first.

What do you think about it? If you are ok with it, I am willing to migrate seadroid to gradle and propose a pull request.

Thanks,
Andreas

### PR DESCRIPTION
**Pull request by amuttsch**
This pull request migrates seadroid to gradle. All dependencies are downloaded from maven central or are provided in the libraries folder.

After pulling seadroid can be build with `./gradlew assembleDebug`. Seadroid gets build and shows possible errors and lint messages. I also changed the travis build to use the android type, but I haven't test it. 

Android SDK versions and build tools can be configured in the root `build.gradle` which is applied for the application as well as the libraries. As a bonus the version code is the number of commits and the version name is the last tag + number of commits since then + hash. When releasing, a new tag should be created, then only the tag name is shown for the version.

Files for maven build were removed because they won't work anymore.

To open seadroid in Android Studio / IntelliJ select import -> from gradle -> next -> finish. The project will be imported and after a short while one can start programming.

When releasing, uncomment the `signingConfigs` lines and build the app with `./gradlew assembleRelease`. An apk should be in `build/output` afterwards.

Fixes #176.

### CODE REVIEW

**Comment by Asfaloth** [comment]
I updated gradle and build tools to be compatible with Android Studio 1.0 as well as merging the master branch to my fork.

**Comment by Asfaloth** [comment]
I thought about your concern regarding the libraries. I saw you have a custom maven library for the two dependencies I currently have in git included and I came up with some possible solutions:

* **include custom maven repo**

  *Advantages:* Nothing to change on your side; no library code in git project
  *Disadvantages:* maven files have to be recreated once libraries are updated (but that is something you have to do right now as well)

* **git submodule**  Add `MarkdownView` and `NewQuickAction` as submodules. 

  *Advantages:* one can simply pull changes via `git submodule update`; no more custom maven repo
  *Disadvantages:* Code is not pulled on checkout, one has to run `git submodule init` and `git submodule update`; on checkout one is always on master, might be difficult when library is beeing updated;

What do you guys think? I'd go with maven, since the libraries won't be updated often (I guess). When you have deceided which way to go I can modify the gradle build script.

**Comment by Asfaloth** [comment]
Merged master and removed some already removed files. They weren't deleted on previous merges.

**Comment by Logan676** [comment]
We appreciate your contributions, I have been starting to use Android Studio these days at my spare time.

**Comment by Logan676** [comment]
@amuttsch Thanks for your excellent work, it works like a charm, gradle build is really powerful and flexible.

But I can\`t merge this PR because it almost modified everything, all useful commit history will be lost. What importantly, since the project structure has changed, other developers who have cloned the project to their local repository will be effected, they will be enforced to use Android Studio. 

I wonder if you can help us to simply add the gradle stuff like what the [Android-Universal-Image-Loader](https://github.com/nostra13/Android-Universal-Image-Loader) did, in order to keep the project structure unchanged.

Another worry is that I have to set the keyStorePassword and push it remotely in order to build via Travis CI, which is not acceptable. Maybe we can remove the sign-released-APK-code-segment if there isn\`t a better way.

Best Regard,
Logan Guo

**Comment by amuttsch** [comment]
I don't see that much of a problem in moving all the files, I did this for my projects too. You don't loose the history, it's a bit more work to get it ;-) I think it's worth it, so you have a clean and standard structure. This way I think it's easier for other devs to get into the code if they already did some Android coding, because the project will use the standard Android folder layout.

Regarding Android Studio: Devs are not forced to use it. They can still use their preferred editor and compile the code with `./gradlew assemble`. Honestly, I wouldn't use anything else than AS or IntelliJ, it's the best IDE I used yet.

`Android-Universal-Image-Loader` uses the default folder structure for libraries too.

Concerning the `keyStorePass`, check out my `build.gradle` script: https://github.com/clementine-player/Android-Remote/blob/master/app/build.gradle#L47 and Line 66. No need for a signing config file anymore.

If you like I can merge the master into my branch and edit the `build.gradle` file.

**Comment by Logan676** [comment]
### COMMENT ONE
> Regarding Android Studio: Devs are not forced to use it. They can still use their preferred editor

Can developers still import the project into Eclipse after you have migrated to Gradle, I think those Eclipse developers will be effected, right?


### COMMENT TWO
> Android-Universal-Image-Loader uses the default folder structure for libraries too.

Sorry, that\`s a mistake, actually what I want to say is keep the Eclipse-way-of-source-structure, and add the Gradle stuff.


### COMMENT THREE
> I thought about your concern regarding the libraries. I saw you have a custom maven library for the two dependencies I currently have in git included and I came up with some possible solutions:

[NewQuickAction](https://github.com/amuttsch/seadroid/tree/master/libraries/NewQuickAction) won\`t be used in the future (starting from seafile-1.9.0), I have changed to use [SlideExpandableListView](https://github.com/tjerkw/Android-SlideExpandableListView) in order to provide a better UI interactions, see #378. `SlideExpandableListView` can be dependent in Gradle way like below
```
compile 'it.sephiroth.android.library.fork.slideexpandable:slideexpandable:1.0.3.1'
```

### COMMENT FOUR
About the another external library [MarkdownView](https://github.com/amuttsch/seadroid/tree/master/libraries/MarkdownView), I think we can remove it as well, because the [markdownview-1.2.jar](https://github.com/haiwen/seadroid/tree/master/libs) is available, we just simply add dependency in `app/build.gradle` like below
```
compile fileTree(dir: 'libs', include: 'markdownview-1.2.jar')
```

### COMMENT FIVE
About publishing the relased APK, every time we are releasing a new version, we will name the tag like `x.x.x`, e.g. 1.8.1 and will name the APK like `seafile-x.x.x`, e.g. seafile-1.8.1. You can find the tags [here](https://github.com/haiwen/seadroid/tags) and releases [here](https://github.com/haiwen/seadroid/releases). So please update the release config in `app/build.gradle` accordingly.

### COMMENT SIX
> If you like I can merge the master into my branch and edit the build.gradle file.

No need to merge the master at this moment, because I will merge several PRs with a [1.9](https://github.com/haiwen/seadroid/milestones/1.9) milestone into master the following days. We plan to release `seafile-1.9.0` first. After that I will come back to notice you to rebase master and evaluate the effects of this patch and merge it.

Thanks

**Comment by forouher** [comment]
@Logan676 
Is this still on your agenda? I'm using Android Studio and I'd love to see the migration to Gradle as it  would make development likely much smoother.

(btw, in case you missed it: Google will deprecate Android Eclipse support at the end of the year: http://android-developers.blogspot.de/2015/06/an-update-on-eclipse-android-developer.html)

**Comment by Logan676** [comment]
Yes, as always. I have to repeat that I am a big fun of Android Studio, have been using it for several months. Also the Gradle way of project building and packing is very flexible and powerful, especially its `Build Variants` and `productFlavors` feature.

@amuttsch please rebase this PR in order to enable the merge button.

Thanks.

**Comment by amuttsch** [comment]
Ok, will do.

**Comment by amuttsch** [comment]
Okay, I updated my branch. One thing: You have to get rid of `ActionBarSherlock`. It is not compatible with API `23` anymore, the app crashes. I had to include `PhotoView` as a library instead of a `jcenter` dependency because of that.

**Comment by Logan676** [comment]
1. Since you have removed `versionName` from AndroidManifest.xml, the Settings --> About Author was effected because it read the version name from it before.
2. better to name the released APK like, `seafile-1.9.2.apk`
3. Though the patch has passed the travis CI build, I didn\`t test the internationalization part yet, because my network is bad at home, I will test it later and see if the i18n part still works


> You have to get rid of ActionBarSherlock. It is not compatible with API 23 anymore, the app crashes. I had to include PhotoView as a library instead of a jcenter dependency because of that.

What do you mean by ActionBarSherlock is not compatible with API23? I have build the patch with API level 23 and run the App on a Android 6.0 (API23) device, both are ok. I wonder why the app crashes if you changed the `PhotoView` to jcenter dependency? I came across a similar issue once, but it is the `universal-image-loader:1.9.3` library, App has an OOM error if changed to jcenter dependency.

**Comment by amuttsch** [comment]
This error is raised when compiled with support library 23: http://stackoverflow.com/questions/32078602/android-java-land-nosuchfielderror-after-update-to-sdk-23

I will have a look at the about page and rename the apk.

**Comment by Logan676** [comment]
@amuttsch The I18N hyperlink in your README.md is incorrect,  use https://www.transifex.com/haiwen/seadroid/ instead. The internationalization part (communicate with Transifex platform) works like a charm from my testing, please update your code based on the latest master branch, fix the comments and we can merge it :)

**Comment by amuttsch** [comment]
@Logan676 : "Since you have removed versionName from AndroidManifest.xml, the Settings --> About Author was effected because it read the version name from it before."

In what way was it affected? For me it says 

    Seafile Android Client

    1.9.3

    Contact us
    ...

**Comment by amuttsch** [comment]
I changed the apk file name and the version code doesn't include the commit hash anymore. I also updated the README to include the correct name.

**Pull request merged**
